name: ci-python-workflow
on: [push]
jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.12'
      - name: Install dependencies
        run: pip install pytest
      - name: Executing tests
        run: pytest
      
